name: Stories app Deployment

on:
  push:
    branches: [ develop ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@master

      - name: Create .env file
        id: env_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ".env"
          encodedString: ${{ secrets.ENV }}

      - name: Move .env into project
        run: mv ${{ steps.env_file.outputs.filePath }} ./www
        
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.8'

      - name: Install dependencies
        working-directory: ./www
        run: | 
          composer install --prefer-dist

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies (Node)
        working-directory: ./www
        run: |
          npm i
          npm run prod

      - name: Run tests
        run: ./vendor/phpunit/phpunit/phpunit
